services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always

    environment:
      POSTGRES_DB: mousebase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

    env_file:
      - .env

volumes:
  postgres_data:
