import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    browser: "src/browser.ts",
    "adapters/nextjs": "src/adapters/nextjs.ts",
    "adapters/express": "src/adapters/express.ts",
    "adapters/nestjs": "src/adapters/nestjs.ts",
    "adapters/cloudflare": "src/adapters/cloudflare.ts",
    "adapters/bun": "src/adapters/bun.ts",
    "adapters/deno": "src/adapters/deno.ts",
    "integrations/langchain": "src/integrations/langchain.ts",
    "integrations/llama-index": "src/integrations/llama-index.ts",
    "integrations/openai-agents": "src/integrations/openai-agents.ts",
    "integrations/crewai": "src/integrations/crewai.ts",
    "integrations/mastra": "src/integrations/mastra.ts",
    "integrations/mcp-server": "src/integrations/mcp-server.ts",
    "cli/index": "cli/index.ts",
  },
  format: ["esm", "cjs"],
  dts: {
    entry: [
      "src/index.ts",
      "src/browser.ts",
      "src/adapters/nextjs.ts",
      "src/adapters/express.ts",
      "src/adapters/nestjs.ts",
      "src/adapters/cloudflare.ts",
      "src/adapters/bun.ts",
      "src/adapters/deno.ts",
    ],
  },
  sourcemap: true,
  clean: true,
  splitting: false,
  external: [
    "mousebase",
    "@nestjs/common",
    "@modelcontextprotocol/sdk/server/index.js",
    "@modelcontextprotocol/sdk/server/stdio.js",
    "@modelcontextprotocol/sdk/types.js",
    "llama-index",
    "langchain",
    "openai",
    "@langchain/core",
    "commander",
  ],
});