"""add api_key_id to projects

Revision ID: 01a3f4ebcb98
Revises: f6e84e97f7a3
Create Date: 2026-07-05 09:55:59.575528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a3f4ebcb98'
down_revision: Union[str, Sequence[str], None] = 'f6e84e97f7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('api_key_id', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_projects_api_key_id'), 'projects', ['api_key_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_api_key_id'), table_name='projects')
    op.drop_column('projects', 'api_key_id')
    # ### end Alembic commands ###
